[package]
edition = "2024"
license = "MIT OR Apache-2.0"
name = "app"
publish = false

[dependencies]
tlsf = { version =  "1.1.0", default-features = false }

js.workspace = true
music.workspace = true
nosync.workspace = true
spur.workspace = true
web.workspace = true
